version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  api:
    build: backend
    container_name: api
    command: bash -c "python app.py"
    volumes:
      - ./media/detects:/code/detects
      - ./media/images:/code/images
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - redis
  recording:
    build: record
    container_name: record
    command: bash -c "python main.py"
    env_file:
      - .env
    volumes:
      - ./media/images:/code/images
      - ./media/videos:/code/videos
    depends_on:
      - redis
  detector:
    build: detector
    container_name: detector
    command: bash -c "python detect.py"
    env_file:
      - .env
    volumes:
      - ./media/images:/code/images
      - ./media/videos:/code/videos
      - ./media/accidents:/code/accidents
      - ./media/detects:/code/detects
    depends_on:
      - redis
  static_server:
    image: nginx
    container_name: static_server
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./web/build:/web:ro
      - ./media:/code/media
    ports:
      - 8001:80